### ISSUE TITLE
国产操作系统环境部署测试出现问题

### ISSUE THREAD

**Issue by TTonlyV5** [zhontai/Admin.Core#109]
问题：
1.部署在uos-server-20-1070a-amd64操作系统，nginx 1.26.2，.Net 8.0.8 （ASP.NET Core Runtime 8.0.8），中台 ZhonTai.Template 8.3.1，使用/usr/local/bin/dotnet /home/wwwroot/MyCompanyName.MyProjectName/MyCompanyName.MyProjectName.Host.dll 出现下面问题：
![1038260431535390af04e8b05a1df3ef8968751f02792763](https://github.com/user-attachments/assets/3059b55e-6fc9-419e-a4ca-ad4320c11550)

2.VS点击发布，没有把Resources文件自动复制到publish。
![10393104315353902913fef6e44832a5f60cd2ee19aa3a58](https://github.com/user-attachments/assets/b54566fc-29ff-4cdf-bb16-6ff6c0db8428)

**Comment by zhontai** [comment]
Resources/Resources.AdminLocalizer.en.json 右键该文件属性设置，复制到输出目录选择如果较新则复制。

**Comment by TTonlyV5** [comment]
dotnet命令，需要找到程序所在目录，然后运行就不报错。
参考：https://www.cnblogs.com/topguntopgun/p/13180093.html

![image](https://github.com/user-attachments/assets/dfc15849-0700-47f9-abee-a0b392eafb56)
