### ISSUE TITLE
赋予部门数据范围，但是编辑用户，和下拉列表选中部门可以选上一级 这样会越权限修改

### ISSUE THREAD

**Issue by YeRenJie** [zhontai/Admin.Core#113]
在用户管理，和部门管理存在越权设置；
![33D TMXODPQPS2Y$18L(83H](https://github.com/user-attachments/assets/b60255b5-d74c-4106-9cb3-1fb1208ffe23)
我的临时修改逻辑：
前端：
部门列表，用户设置 下拉部门列表修改 
1、dataScope：数据范围 全部1,本部门和下级部门2,本部门3,本人数据4，指定部门5
判断如果是1 不处理，2 3 4设置根节点为当前用户部门orgId（目前用户只支持单部门设置），5 不做树形列表，直接填充下拉列表

后端：1、机构列表注释返回父级机构，默认向下获取
2、用户登录多返回两个值，当前用户部门id，数据范围 （部门id用于设置列表根）。

**Comment by zhontai** [comment]
计划中
