### ISSUE TITLE
赋予用户查看权限依旧不能查询

### ISSUE THREAD

**Issue by dearyangyu** [zhontai/Admin.Core#114]
![image](https://github.com/user-attachments/assets/41d31a83-b220-4ccf-8fb1-47dbe96a4b16)
当我为套餐添加了查看权限之后，分页查询没有问题，但是根据ID查询时显示权限不足
![image](https://github.com/user-attachments/assets/51d748a9-58fb-4382-ad9f-c17d6c8f0cf8)
![image](https://github.com/user-attachments/assets/a06ab168-7301-42e3-9fe9-7ebc79bf6ea3)

**Comment by zhontai** [comment]
单个查询用在修改操作上
