### ISSUE TITLE
Localization English Option

### ISSUE THREAD

**Issue by papyr** [zhontai/Admin.Core#15]
Hello can you allow english please

**Comment by 877198799** [comment]
Considered after version 1.6.0

**Comment by zhontai** [comment]
Considered after version 1.6.0

**Comment by papyr** [comment]
hello, any chance we can get an English version, many developers would love this. this is much better than ABP for main stream developers!!

**Comment by zhontai** [comment]
In version 8.3.0, we have added support for internationalization with English translation.
To configure the en (English) environment in appconfig.lang.
