### ISSUE TITLE
点几个菜单都很卡，原因未知

### ISSUE THREAD

**Issue by dmhai** [zhontai/Admin.Core#28]
第一次进入后台，以前没访问过。

点员工管理，卡住很久(没有心理准备,没计算时间)才打开新tab，再次进入后台之后一切正常，无法重现。

直接点租户管理，卡住近10s才打开新tab，再次进入后台之后一切正常，无法重现。

后面的没点了。

换浏览器也无法重现，估计跟缓存有关？

**Comment by zhontai** [comment]
首次加载请求资源较耗时间，新版已使用按需加载速度会更快
