### ISSUE TITLE
cs文件文件编码

### ISSUE THREAD

**Issue by tytannial** [zhontai/Admin.Core#3]
似乎不是所有文件的编码都是utf8的，最近几次提交的文件中混有936编码文件。

**Comment by zhontai** [comment]
哪几个文件编码有问题，这边好修正？

**Comment by tytannial** [comment]
\Admin.Core\Admin.Core.Services\Admin\Permission\Input\PermissionAddDotInput.cs
\Admin.Core\Admin.Core.Services\Admin\Permission\Input\PermissionUpdateDotInput.cs
\Admin.Core\Admin.Core.Services\Admin\Permission\Input\PermissionAddApiInput.cs

**Comment by zhontai** [comment]
已修复
