### ISSUE TITLE
列表点击编辑背景会闪一下，新增不会

### ISSUE THREAD

**Issue by liaozb** [zhontai/Admin.Core#52]
![image](https://github.com/zhontai/Admin.Core/assets/12622501/5cdfee09-fe0c-47c3-aec2-1d1628359361)

**Comment by zhontai** [comment]
修改会异步请求，增加loading效果引起，后续看如何优化

**Comment by gudufy** [comment]
> 修改会异步请求，增加loading效果引起，后续看如何优化

可以用顶部loading条

**Comment by yimogit** [comment]
显示弹窗，然后将数据加载loading加载到弹窗或许会更好一点，当然target的类名自定义更好
不过需要注意下渲染2次的问题（看你会有模型变更，视图没有变的情况）
```
state.showDialog = true
  if (row.id > 0) {
    const res = await new OrgApi().get({ id: row.id }, { loading: true, loadingOptions: { target: '.el-dialog' } })
...
//state.showDialog = true
```

![image](https://github.com/zhontai/Admin.Core/assets/15975059/845aa723-6a2e-4c08-99dd-b092b4d2689a)

**Comment by yimogit** [comment]
保持遮罩背景色和默认loading的遮罩颜色一样就好，默认是 rgba(0,0,0,0.5)
.el-overlay {
  background-color: rgba(0,0,0,0.5);
}

loadingOptions = {
    background: 'rgba(0,0,0,0.5)'
  }
@zhontai 可以加上默认值
![image](https://github.com/zhontai/Admin.Core/assets/15975059/d821d411-7108-433c-8d66-6a3b3e8d31e9)

**Comment by zhontai** [comment]
@yimogit 提个pr
