### ISSUE TITLE
Api接口怎么同步

### ISSUE THREAD

**Issue by BruceLuo2** [zhontai/Admin.Core#63]
显示成功, 但实际后台似乎是404? 这个应该改哪里
![image](https://github.com/zhontai/Admin.Core/assets/33817573/a89bb960-e3e4-4fb5-8f8b-db9b18d4c8f3)

**Comment by zhontai** [comment]
直接修改同步按钮接口地址为swagger地址，如果是项目模板则是app/swagger-resources
也可以直接升级到新版本，通过接口获取地址同步

**Comment by yimogit** [comment]
这里加个projects的bool值过滤下怎么样，启用了的才生成 @zhontai

**Comment by zhontai** [comment]
> 这里加个projects的bool值过滤下怎么样，启用了的才生成 @zhontai

可以考虑前端弹框勾选判断生成哪一个会更好。

**Comment by yimogit** [comment]
> > 这里加个projects的bool值过滤下怎么样，启用了的才生成 @zhontai
> 
> 可以考虑前端弹框勾选判断生成哪一个会更好。

目前是想要在swagger中分组显示，前缀都是 admin/ ， /admin/swagger-resources 可以把所有模块分组接口返回，其他的也同步不了比如 /app/swagger-resources是不存在的

**Comment by zhontai** [comment]
> > > 这里加个projects的bool值过滤下怎么样，启用了的才生成 @zhontai
> > 
> > 
> > 可以考虑前端弹框勾选判断生成哪一个会更好。
> 
> 目前是想要在swagger中分组显示，前缀都是 admin/ ， /admin/swagger-resources 可以把所有模块分组接口返回，其他的也同步不了比如 /app/swagger-resources是不存在的

需要考虑多人协作一个项目分组接口时，代码拉取不及时，同步其它模块接口会有问题。所以勾选同步是比较放心的做法，只同步自己开发的模块接口。这里牵涉到多项目接口，要是单体项目接口可以不用考虑这些问题。
