### ISSUE TITLE
同步数据希望添加一个通用的方法 现在都是针对类写的

### ISSUE THREAD

**Issue by YeRenJie** [zhontai/Admin.Core#77]
![CY@UQD(D(()WGKPZ%SP(QFU](https://github.com/zhontai/Admin.Core/assets/21137090/433519fa-832e-49e0-a0ff-40402c4016a8)

**Comment by yimogit** [comment]
![image](https://github.com/zhontai/Admin.Core/assets/15975059/82495246-7261-4161-bfc2-7d78b755d4e8)
可以改成泛型
