### ISSUE TITLE
[Bug]上传文件到其他目录(如临时目录)后LinkAddress错误

### ISSUE THREAD

**Issue by padixa** [zhontai/Admin.Core#81]
显示的是服务端地址+本地临时目录绝对路径. 应该返回绝对路径, 或增加一个字段显示当前文件本地完整路径.

**Comment by zhontai** [comment]
需要测试重现后修复

**Comment by padixa** [comment]
另外文件管理没必要显示上传到临时文件夹上的文件吧.  文件管理应该改名为: 上传管理更合适.    
希望能做个真正的文件管理,  指向某个file文件夹下的所有文件, 能查看目录列表和文件列表, 能下载, 上传, 重命名

**Comment by zhontai** [comment]
这一块会优先考虑多OSS这一块设计，本地相对用得不多

**Comment by padixa** [comment]
上传到临时目录后没必要写入到数据库吧,  或者提供选项是否写入到数据库,  不然即便打开了文件管理, 也下载不到, 毕竟上传到临时目录里.
