### ISSUE TITLE
菜单权限显示不正确

### ISSUE THREAD

**Issue by TTonlyV5** [zhontai/Admin.Core#83]
![QQ_1720693720932](https://github.com/zhontai/Admin.Core/assets/20924375/b8880312-86ae-469a-baed-850c3c839352)
![QQ_1720693744671](https://github.com/zhontai/Admin.Core/assets/20924375/46816006-ae47-4571-83d4-e65d724d95d3)

**Comment by zhontai** [comment]
没太看明白

**Comment by TTonlyV5** [comment]
已经设置权限应该都勾选起来有的，如下显示，现在是没有勾选的
![QQ_1720749912731](https://github.com/user-attachments/assets/bc123a74-78ed-4838-9d41-c30dc3389fa1)

**Comment by zhontai** [comment]
拉取最新代码后，dbconfig强制更新开启，或者将db库清除后再生成试试。
重新没有发现你说的问题
