### ISSUE TITLE
后端判断是否有某个权限编码权限的时候，代码获取权限编码写法在oracle数据库获取不到，导致后台判断权限编码失败

### ISSUE THREAD

**Issue by hymsnow** [zhontai/Admin.Core#85]
出错位置 ：UserService的GetPermissionAsync方法
问题说明：
就是后端判断是否有某个权限编码权限的时候，代码获取权限编码 使用这个 !string.IsNullOrWhiteSpace(p.Code) 判断，在oracle数据库是执行返回是不出结果的，改成 p.Code ！=null 是有结果出现的
![3E60C4B9F9A8C14213C76B835013B221](https://github.com/user-attachments/assets/c72328b6-09f3-4a96-907b-a117de256908)

**Comment by zhontai** [comment]
这个条件修改，会在其它数据库测试后更新
