### ISSUE TITLE
Mysql5.6.45下创建索引出错。

### ISSUE THREAD

**Issue by 5653325** [zhontai/Admin.Core#9]
CREATE UNIQUE INDEX `uk_document_image_documentid_url` ON `admindb`.`ad_document_image`(`DocumentId`, `Url`);
Index column size too large. The maximum column size is 767 bytes.

**Comment by 877198799** [comment]
缩短建索引字段varchar的字符数
或者启用innodb_large_prefix，那么限制值会增加到3072
