### ISSUE TITLE
HEX版本冲突

### ISSUE THREAD

**Issue by yesdadou** [zhontai/Admin.Core#90]
nuget安装了net-questdb-client之后，就会报错：错误	CS0433	类型“Hex”同时存在于“BouncyCastle.Crypto, Version=1.9.0.0, Culture=neutral, PublicKeyToken=null”和“BouncyCastle.Cryptography, Version=2.0.0.0, Culture=neutral, PublicKeyToken=072edcf4a5328938”中

**Comment by zhontai** [comment]
更新 net-questdb-client至2.0.0
ZhonTai.Common的BouncyCastle.Cryptography更新至2.4.0，让他们保持版本一致就没有问题
