### ISSUE TITLE
日志系统的优化建议

### ISSUE THREAD

**Issue by share36** [zhontai/Admin.Core#96]
1、操作日志增加描述信息及详细信息：帮助用户快速查找到对自己有用的日志。（目前日志只是接口日志，没有操作的日志）
 a、操作成功日志项，操作消息应该有简短的描述，供用户快速定位日志，可以点击查看详细内容的方式查看详细的日志内容；
  如：增加用户：应该可以看到具体增加的是谁。修改用户信息：应该能看到修改了谁的信息。使用详细信息查看具体的新增或修改内容。
 b、查询项目增加 日期段、IP、模块、操作项等过滤条件。
2、增加安全日志：对一些 核心功能 或 非常规操作 的权限应该触发安全日志。

**Comment by zhontai** [comment]
预计在8.4版本中考虑

**Comment by zhontai** [comment]
增加安全日志：对一些 核心功能 或 非常规操作 的权限应该触发安全日志。这一项不太符合操作日志的功能，暂不考虑
